const axios = require('axios');

class ConfluenceTool {
    constructor(url, email, token) {
        this.url = (url || '').replace(/\/$/, '');
        this.email = email;
        this.token = token;

        const authString = Buffer.from(`${this.email}:${this.token}`).toString('base64');
        this.headers = {
            'Authorization': `Basic ${authString}`,
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        };
    }

    async createPage(spaceKey, title, contentMarkdown, parentId = null) {
        const apiUrl = `${this.url}/wiki/rest/api/content`;
        
        // Simple Markdown-to-XHTML conversion (wrapping in pre for now)
        const xhtmlContent = `<p><em>Generated by TestingBuddy AI</em></p><pre>${contentMarkdown}</pre>`;
        
        const payload = {
            type: 'page',
            title: title,
            space: { key: spaceKey },
            body: {
                storage: {
                    value: xhtmlContent,
                    representation: 'storage'
                }
            }
        };

        if (parentId) {
            payload.ancestors = [{ id: parentId }];
        }

        try {
            const response = await axios.post(apiUrl, payload, {
                headers: this.headers,
                timeout: 20000
            });
            return response.data;
        } catch (error) {
            const errStr = error.response ? `${error.response.status} - ${JSON.stringify(error.response.data)}` : error.message;
            throw new Error(`Confluence Publish failed: ${errStr}`);
        }
    }
}

module.exports = ConfluenceTool;
