/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "app-red": "#E60012",
        "app-dark-red": "#b7000c",
        "app-blue": "#004098",
        "app-dark-blue": "#002d6b",
        "inverse-primary": "#ffb4aa",
        "background": "#fef7ff",
        "secondary-fixed-dim": "#b0c6ff",
        "primary": "#b7000c",
        "surface": "#fef7ff",
        "surface-tint": "#c0000d",
        "surface-container-low": "#f9f1fd",
        "inverse-surface": "#322f37",
        "surface-container": "#f3ebf7",
        "on-surface": "#1d1a22",
        "on-error": "#ffffff",
        "on-primary-container": "#fff7f6",
        "on-tertiary-fixed-variant": "#464749",
        "surface-container-high": "#ede6f1",
        "primary-fixed": "#ffdad5",
        "error": "#ba1a1a",
        "on-tertiary-container": "#f9f8fa",
        "on-secondary-container": "#003581",
        "tertiary": "#595a5c",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d9e2ff",
        "on-background": "#1d1a22",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#930007",
        "tertiary-fixed": "#e3e2e4",
        "primary-fixed-dim": "#ffb4aa",
        "tertiary-container": "#717274",
        "surface-dim": "#dfd7e3",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#1a1c1d",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e7e0eb",
        "inverse-on-surface": "#f6eefa",
        "outline": "#946e69",
        "on-surface-variant": "#5f3f3b",
        "surface-container-highest": "#e7e0eb",
        "on-secondary-fixed": "#001945",
        "primary-container": "#e60012",
        "on-secondary-fixed-variant": "#04429a",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-bright": "#fef7ff",
        "tertiary-fixed-dim": "#c6c6c8",
        "secondary-container": "#79a1fe",
        "outline-variant": "#e9bcb6",
        "on-primary-fixed": "#410001",
        "secondary": "#2d5bb3"
      },
      fontFamily: {
        headline: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

