import requests
import json
from typing import Dict, Any

class ConfluenceTool:
    def __init__(self, url: str, email: str, token: str):
        self.url = url.rstrip("/")
        self.auth = (email, token)
        self.headers = {
            "Accept": "application/json",
            "Content-Type": "application/json"
        }

    def create_page(self, space_key: str, title: str, content_markdown: str, parent_id: str = None) -> Dict[str, Any]:
        """Create a new page in Confluence using Storage Format (XHTML)."""
        api_url = f"{self.url}/wiki/rest/api/content"
        
        # Simple Markdown-to-XHTML conversion (just wrapping pre-formatted text for now)
        # In a real app, we'd use a markdown library to convert to clean XHTML.
        # For this POC, we'll use a simple conversion style.
        xhtml_content = f"<p><em>Generated by TestingBuddy AI</em></p><pre>{content_markdown}</pre>"
        
        payload = {
            "type": "page",
            "title": title,
            "space": {"key": space_key},
            "body": {
                "storage": {
                    "value": xhtml_content,
                    "representation": "storage"
                }
            }
        }
        
        if parent_id:
            payload["ancestors"] = [{"id": parent_id}]

        response = requests.post(api_url, auth=self.auth, headers=self.headers, json=payload, timeout=20)
        
        if response.status_code not in [200, 201]:
            raise Exception(f"Confluence Publish failed: {response.status_code} - {response.text}")
            
        return response.json()
